name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MSBuild_Path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Clean up
      run: |
        "${{env.MSBuild_Path}}" ${{github.workspace}}\LenovoLegionToolkit.sln /t:Clean /p:Configuration=Release
    - name: Build
      run: .\make.bat "${{env.MSBuild_Path}}"
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: installer
        path: build_installer\LenovoLegionToolkitSetup.exe
